# Set nginx base image
FROM nginx

# File Author / Maintainer
LABEL maintainer="Miguel Salinas Gancedo"

# Copy custom configuration file from the current directory
COPY standalone/nginx.conf /etc/nginx/nginx.conf